name: Bug-busters-CI

on:
  push:
    branches: ["development"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: |
            npm run lint
            npm run test
